const toggle=document.querySelector('.nav-toggle');const nav=document.querySelector('nav');toggle.addEventListener('click',()=>{const open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',String(open));toggle.setAttribute('aria-label',open?'메뉴 닫기':'메뉴 열기');});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');toggle.setAttribute('aria-expanded','false');toggle.setAttribute('aria-label','메뉴 열기');}));
document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(b=>b.setAttribute('aria-selected',String(b===button)));document.querySelectorAll('.menu-card').forEach(card=>card.hidden=button.dataset.filter==='all'?(card.hasAttribute('data-dessert-only')||card.hasAttribute('data-drink-only')):card.dataset.category!==button.dataset.filter);}));
const menus={americano:{title:'몽글 아이스아메리카노',description:'향긋한 커피를 얼음과 함께 시원하고 깔끔하게 즐기는 한 잔입니다.',pairing:'팥 오메기떡과 함께 커피의 향과 달콤함을 즐겨보세요.'},sesame:{title:'흑임자 오메기떡',description:'흑임자의 깊은 고소함과 쫀득한 떡을 함께 즐기는 디저트입니다.',pairing:'몽글 카페라떼와 함께 즐겨보세요.'},citrus:{title:'감귤 오메기떡',description:'감귤의 산뜻한 풍미를 담은 제주 디저트입니다.',pairing:'부드러운 카페라떼와 산뜻한 한 입.'},rice:{title:'팥 오메기떡',description:'팥고물의 포근한 달콤함과 쫀득한 초록색 떡의 식감을 함께 즐기는 대표 디저트입니다.',pairing:'몽글 카페라떼와 함께 부드럽게 즐겨보세요.'},latte:{title:'몽글 카페라떼',description:'향긋한 커피에 우유의 부드러움을 더한 한 잔. 오메기떡과 함께 여유로운 오후를 즐겨보세요.',pairing:'팥 오메기떡 한 입, 라떼 한 모금.'},matcha:{title:'말차 라떼',description:'말차의 은은한 쌉싸름함을 우유가 부드럽게 감싸는 음료입니다.',pairing:'달콤한 팥 오메기떡과 말차의 깊은 맛을 함께.'}};const dialog=document.querySelector('dialog');document.querySelectorAll('[data-menu]').forEach(button=>button.addEventListener('click',()=>{const item=menus[button.dataset.menu];document.querySelector('#dialog-title').textContent=item.title;document.querySelector('#dialog-description').textContent=item.description;document.querySelector('#dialog-pairing').textContent=item.pairing;renderFacts(button.dataset.menu);dialog.showModal();}));document.querySelectorAll('.close-dialog,.close-action').forEach(button=>button.addEventListener('click',()=>dialog.close()));dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});


const flavorFacts={rice:['달콤함 · 쫀득함','팥 고물'],sesame:['고소함 · 쫀득함','흑임자 풍미'],citrus:['산뜻함 · 쫀득함','감귤 풍미'],latte:['부드러움 · 커피 향','커피와 우유'],matcha:['은은한 쌉싸름함 · 부드러움','말차와 우유'],americano:['깔끔함 · 커피 향','시원하게 즐기는 커피']};
function renderFacts(key){const node=document.querySelector('#menu-facts');node.replaceChildren();const values=flavorFacts[key];['맛의 특징','메뉴 포인트'].forEach((label,index)=>{const row=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=values[index];row.append(dt,dd);node.append(row);});}
const combos={classic:{title:'팥 오메기떡 + 아이스아메리카노',copy:'팥의 달콤함에 깔끔한 커피 한 모금. 처음 만나는 몽글제주에 어울리는 조합이에요.',dessert:'rice',drink:'americano'},nutty:{title:'흑임자 오메기떡 + 말차 라떼',copy:'흑임자의 고소함과 말차의 은은한 쌉싸름함. 깊은 풍미를 천천히 즐겨보세요.',dessert:'sesame',drink:'matcha'},fresh:{title:'감귤 오메기떡 + 카페라떼',copy:'감귤의 산뜻함을 부드러운 카페라떼와 함께. 기분 전환이 필요한 오후에 골라보세요.',dessert:'citrus',drink:'latte'}};let chosenTaste='classic';document.querySelectorAll('[data-taste]').forEach(button=>button.addEventListener('click',()=>{chosenTaste=button.dataset.taste;document.querySelectorAll('[data-taste]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));document.querySelector('#combo-title').textContent=combos[chosenTaste].title;document.querySelector('#combo-copy').textContent=combos[chosenTaste].copy;const photo=document.querySelector('#combo-photo'),img=document.querySelector('#combo-image');photo.className='combo-photo combo-'+chosenTaste;img.src='assets/combo-'+chosenTaste+'.webp';img.alt=chosenTaste==='classic'?'팥 오메기떡과 커피':chosenTaste==='nutty'?'흑임자 오메기떡과 아이스 말차 라떼':'감귤 오메기떡과 아이스 카페라떼';}));
function showComboMenu(kind){const key=combos[chosenTaste][kind],item=menus[key];document.querySelector('#dialog-title').textContent=item.title;document.querySelector('#dialog-description').textContent=item.description;document.querySelector('#dialog-pairing').textContent=item.pairing;renderFacts(key);dialog.showModal();}document.querySelector('#combo-dessert').addEventListener('click',()=>showComboMenu('dessert'));document.querySelector('#combo-drink').addEventListener('click',()=>showComboMenu('drink'));
const filters=[...document.querySelectorAll('[data-filter]')];filters.forEach((button,index)=>{button.tabIndex=index===0?0:-1;button.addEventListener('click',()=>filters.forEach(b=>b.tabIndex=b===button?0:-1));button.addEventListener('keydown',e=>{let target;if(e.key==='ArrowRight')target=(index+1)%filters.length;if(e.key==='ArrowLeft')target=(index+filters.length-1)%filters.length;if(e.key==='Home')target=0;if(e.key==='End')target=filters.length-1;if(target!==undefined){e.preventDefault();filters[target].focus();filters[target].click();}});});

// Warm the three small pairing photos for instant taste switching.
['classic','nutty','fresh'].forEach(taste=>{const image=new Image();image.src='assets/combo-'+taste+'.webp';});
